version: '3.4'

services:
  matemachine.admin-panel.api:
    build:
      context: .
      dockerfile: ./src/MateMachine.AdminPanel.Api/Dockerfile
      args:
        NUGET_SOURCE: ${NUGET_SOURCE}
        PIPELINE_USER: ${PIPELINE_USER}
        PIPELINE_TOKEN: ${PIPELINE_TOKEN}
